name = "CreateWithFriends"
author = "Shyrogan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfd4b41bcd814dd95cdb85fa5620736a0fe7d1621a38f9c60e233c09a3d47479"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.43"
