name = "CreateWithFriends"
author = "Shyrogan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb9d919a1a8c25dfe2c68169091e1ce99c86f47f07bc545adc4691c23e46d095"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.43"
