name = "CreateWithFriends"
author = "Shyrogan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac221c0f100ecaa53acec51e83b0855483e6dd56f3ca28e9ca8088ebde09a340"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.43"
